export const countries = [
  { key: 'af', label: 'Afghanistan' },
  { key: 'za', label: 'Afrique du Sud' },
  { key: 'al', label: 'Albanie' },
  { key: 'dz', label: 'Algérie' },
  { key: 'de', label: 'Allemagne' },
  { key: 'ad', label: 'Andorre' },
  { key: 'ao', label: 'Angola' },
  { key: 'ag', label: 'Antigua-et-Barbuda' },
  { key: 'sa', label: 'Arabie saoudite' },
  { key: 'ar', label: 'Argentine' },
  { key: 'am', label: 'Arménie' },
  { key: 'au', label: 'Australie' },
  { key: 'at', label: 'Autriche' },
  { key: 'az', label: 'Azerbaïdjan' },
  { key: 'bs', label: 'Bahamas' },
  { key: 'bh', label: 'Bahreïn' },
  { key: 'bd', label: 'Bangladesh' },
  { key: 'bb', label: 'Barbade' },
  { key: 'be', label: 'Belgique' },
  { key: 'bz', label: 'Belize' },
  { key: 'bj', label: 'Bénin' },
  { key: 'bt', label: 'Bhoutan' },
  { key: 'by', label: 'Biélorussie' },
  { key: 'mm', label: 'Birmanie' },
  { key: 'bo', label: 'Bolivie' },
  { key: 'ba', label: 'Bosnie-Herzégovine' },
  { key: 'bw', label: 'Botswana' },
  { key: 'br', label: 'Brésil' },
  { key: 'bn', label: 'Brunei' },
  { key: 'bg', label: 'Bulgarie' },
  { key: 'bf', label: 'Burkina Faso' },
  { key: 'bi', label: 'Burundi' },
  { key: 'kh', label: 'Cambodge' },
  { key: 'cm', label: 'Cameroun' },
  { key: 'ca', label: 'Canada' },
  { key: 'cv', label: 'Cap-Vert' },
  { key: 'cf', label: 'République centrafricaine' },
  { key: 'cl', label: 'Chili' },
  { key: 'cn', label: 'Chine' },
  { key: 'cy', label: 'Chypre' },
  { key: 'co', label: 'Colombie' },
  { key: 'km', label: 'Comores' },
  { key: 'cg', label: 'Congo-Brazzaville' },
  { key: 'cd', label: 'Congo-Kinshasa' },
  { key: 'kp', label: 'Corée du Nord' },
  { key: 'kr', label: 'Corée du Sud' },
  { key: 'cr', label: 'Costa Rica' },
  { key: 'ci', label: "Côte d'Ivoire" },
  { key: 'hr', label: 'Croatie' },
  { key: 'cu', label: 'Cuba' },
  { key: 'dk', label: 'Danemark' },
  { key: 'dj', label: 'Djibouti' },
  { key: 'dm', label: 'Dominique' },
  { key: 'eg', label: 'Égypte' },
  { key: 'ae', label: 'Émirats arabes unis' },
  { key: 'ec', label: 'Équateur' },
  { key: 'er', label: 'Érythrée' },
  { key: 'es', label: 'Espagne' },
  { key: 'ee', label: 'Estonie' },
  { key: 'us', label: 'États-Unis' },
  { key: 'et', label: 'Éthiopie' },
  { key: 'fj', label: 'Fidji' },
  { key: 'fi', label: 'Finlande' },
  { key: 'fr', label: 'France' },
  { key: 'ga', label: 'Gabon' },
  { key: 'gm', label: 'Gambie' },
  { key: 'ge', label: 'Géorgie' },
  { key: 'gh', label: 'Ghana' },
  { key: 'gr', label: 'Grèce' },
  { key: 'gd', label: 'Grenade' },
  { key: 'gt', label: 'Guatemala' },
  { key: 'gn', label: 'Guinée' },
  { key: 'gq', label: 'Guinée équatoriale' },
  { key: 'gw', label: 'Guinée-Bissau' },
  { key: 'gy', label: 'Guyana' },
  { key: 'ht', label: 'Haïti' },
  { key: 'hn', label: 'Honduras' },
  { key: 'hu', label: 'Hongrie' },
  { key: 'in', label: 'Inde' },
  { key: 'id', label: 'Indonésie' },
  { key: 'iq', label: 'Irak' },
  { key: 'ir', label: 'Iran' },
  { key: 'ie', label: 'Irlande' },
  { key: 'is', label: 'Islande' },
  { key: 'il', label: 'Israël' },
  { key: 'it', label: 'Italie' },
  { key: 'jm', label: 'Jamaïque' },
  { key: 'jp', label: 'Japon' },
  { key: 'jo', label: 'Jordanie' },
  { key: 'kz', label: 'Kazakhstan' },
  { key: 'ke', label: 'Kenya' },
  { key: 'kg', label: 'Kirghizistan' },
  { key: 'ki', label: 'Kiribati' },
  { key: 'kw', label: 'Koweït' },
  { key: 'la', label: 'Laos' },
  { key: 'ls', label: 'Lesotho' },
  { key: 'lv', label: 'Lettonie' },
  { key: 'lb', label: 'Liban' },
  { key: 'lr', label: 'Libéria' },
  { key: 'ly', label: 'Libye' },
  { key: 'li', label: 'Liechtenstein' },
  { key: 'lt', label: 'Lituanie' },
  { key: 'lu', label: 'Luxembourg' },
  { key: 'mk', label: 'Macédoine du Nord' },
  { key: 'mg', label: 'Madagascar' },
  { key: 'my', label: 'Malaisie' },
  { key: 'mw', label: 'Malawi' },
  { key: 'mv', label: 'Maldives' },
  { key: 'ml', label: 'Mali' },
  { key: 'mt', label: 'Malte' },
  { key: 'ma', label: 'Maroc' },
  { key: 'mh', label: 'Îles Marshall' },
  { key: 'mu', label: 'Maurice' },
  { key: 'mr', label: 'Mauritanie' },
  { key: 'mx', label: 'Mexique' },
  { key: 'fm', label: 'Micronésie' },
  { key: 'md', label: 'Moldavie' },
  { key: 'mc', label: 'Monaco' },
  { key: 'mn', label: 'Mongolie' },
  { key: 'me', label: 'Monténégro' },
  { key: 'mz', label: 'Mozambique' },
  { key: 'na', label: 'Namibie' },
  { key: 'nr', label: 'Nauru' },
  { key: 'np', label: 'Népal' },
  { key: 'ni', label: 'Nicaragua' },
  { key: 'ne', label: 'Niger' },
  { key: 'ng', label: 'Nigéria' },
  { key: 'no', label: 'Norvège' },
  { key: 'nz', label: 'Nouvelle-Zélande' },
  { key: 'om', label: 'Oman' },
  { key: 'ug', label: 'Ouganda' },
  { key: 'uz', label: 'Ouzbékistan' },
  { key: 'pk', label: 'Pakistan' },
  { key: 'pw', label: 'Palaos' },
  { key: 'pa', label: 'Panama' },
  { key: 'pg', label: 'Papouasie-Nouvelle-Guinée' },
  { key: 'py', label: 'Paraguay' },
  { key: 'nl', label: 'Pays-Bas' },
  { key: 'pe', label: 'Pérou' },
  { key: 'ph', label: 'Philippines' },
  { key: 'pl', label: 'Pologne' },
  { key: 'pt', label: 'Portugal' },
  { key: 'qa', label: 'Qatar' },
  { key: 'ro', label: 'Roumanie' },
  { key: 'gb', label: 'Royaume-Uni' },
  { key: 'ru', label: 'Russie' },
  { key: 'rw', label: 'Rwanda' },
  { key: 'kn', label: 'Saint-Christophe-et-Niévès' },
  { key: 'sm', label: 'Saint-Marin' },
  { key: 'vc', label: 'Saint-Vincent-et-les-Grenadines' },
  { key: 'lc', label: 'Sainte-Lucie' },
  { key: 'sv', label: 'Salvador' },
  { key: 'ws', label: 'Samoa' },
  { key: 'st', label: 'Sao Tomé-et-Principe' },
  { key: 'sn', label: 'Sénégal' },
  { key: 'rs', label: 'Serbie' },
  { key: 'sc', label: 'Seychelles' },
  { key: 'sl', label: 'Sierra Leone' },
  { key: 'sg', label: 'Singapour' },
  { key: 'sk', label: 'Slovaquie' },
  { key: 'si', label: 'Slovénie' },
  { key: 'so', label: 'Somalie' },
  { key: 'sd', label: 'Soudan' },
  { key: 'ss', label: 'Soudan du Sud' },
  { key: 'lk', label: 'Sri Lanka' },
  { key: 'se', label: 'Suède' },
  { key: 'ch', label: 'Suisse' },
  { key: 'sr', label: 'Suriname' },
  { key: 'sz', label: 'Eswatini' },
  { key: 'sy', label: 'Syrie' },
  { key: 'tj', label: 'Tadjikistan' },
  { key: 'tz', label: 'Tanzanie' },
  { key: 'td', label: 'Tchad' },
  { key: 'cz', label: 'Tchéquie' },
  { key: 'th', label: 'Thaïlande' },
  { key: 'tl', label: 'Timor oriental' },
  { key: 'tg', label: 'Togo' },
  { key: 'to', label: 'Tonga' },
  { key: 'tt', label: 'Trinité-et-Tobago' },
  { key: 'tn', label: 'Tunisie' },
  { key: 'tm', label: 'Turkménistan' },
  { key: 'tr', label: 'Turquie' },
  { key: 'tv', label: 'Tuvalu' },
  { key: 'ua', label: 'Ukraine' },
  { key: 'uy', label: 'Uruguay' },
  { key: 'va', label: 'Vatican' },
  { key: 've', label: 'Venezuela' },
  { key: 'vn', label: 'Viêt Nam' },
  { key: 'ye', label: 'Yémen' },
  { key: 'zm', label: 'Zambie' },
  { key: 'zw', label: 'Zimbabwe' },
];
